### ISSUE TITLE
Using security requirements, identify five assurance claims

### ISSUE THREAD

**Issue by caseyschmitz** [caseyschmitz/CYBR8420-GotRoot#35]

**Comment by Guerrias** [comment]
I have two propositions of claim for the current assignment: 
-Data is acceptably secure against unauthorized access.
-The encryption key generation minimize the success of brute force attacks.

**Comment by caseyschmitz** [comment]
I think we can approach the idea of securely managing secrets as a top-level claim followed by claims that address some of the potential misuse cases that were identified. I.e.,
### Claim: "The system is acceptably secure against unauthorized access of secrets."
* Sub-claim: "The system is acceptably secure against unauthorized access to secrets transmitted to/from client applications."
* Sub-claim: "The system is acceptably secure against unauthorized access to secrets stored on client applications."

**Comment by caseyschmitz** [comment]
> -Data is acceptably secure against unauthorized access.

I think we can apply this more specifically to a few of our security requirements. See my [last comment](https://github.com/caseyschmitz/CYBR8420-GotRoot/issues/35#issuecomment-539288850).

**Comment by sdfrench** [comment]
Here is a quick brain dump. Im not exactly clear if we are supposed to focus specifically on our application or look at security managers in general. (if its the later then substitute “The security manager” for “Bitwarden”)  I listed a couple of top sub-claims for each as well.


Bitwarden prevents network eavesdropping during client-server communications.
	- client side encryption
	- TLS

Bitwarden is acceptably secure against login attacks
	- Master Password strength (brute force)
	- Key Derivation (rainbow tables)
       - Any other security features on server portal?

Bitwarden prevents unauthorized access to secret data.
	- End to end encryption
	- Master Password only known to vault owner
	- Master Password is only kept client side

Bitwarden adequately prevents exposure to clear text attacks.
	- Each secret is encrypted/decrypted individuals
	- Protection of decryption key/s
	- No Clear text at rest

Bitwarden adequately prohibits unauthorized access to shared secrets.
	- Asymmetric encryption
	- Server side programatic enforcement ?

**Comment by caseyschmitz** [comment]
I think these can all be easily converted to 'appropriate' claim format. Should we each take one to expand on?

**Comment by Guerrias** [comment]
@caseyschmitz, I have notice all our staff is about encryptions so felt like using each point to just talk about the encryption a little bit repetitive because we will use the same hypothesis on all of them.

**Comment by sdfrench** [comment]
yeah I had the same concern but since our tool is so heavily based on encryption it may be hard to get around it. Even so we can discus different aspects, TLS, Asymmetric, Key protection, Key derivation, etc..  Might be a good question for Dr. Gandhi if we can't come up with other cases.

**Comment by Guerrias** [comment]
yeah we my refer to him. We can submit what we have and according to his judgement we will see if we need to group some claims into one or no.

**Comment by caseyschmitz** [comment]
Claims submitted to Dr Gandhi by @Guerrias :
-Bitwarden prevents network eavesdropping during client-server communications;
-Bitwarden is acceptably secure against login attacks;
-Bitwarden prevents unauthorized access to secret data;
-Bitwarden adequately prevents exposure to clear text attacks;
-Bitwarden adequately prohibits unauthorized access to shared secrets.

**Comment by caseyschmitz** [comment]
Dr Gandhi's feedback:
The first three claims are good. RE #4, I am not sure how software can prevent "exposure". Exposure is something that can only be controlled in the environment and by how the people installing it choose to provide access. Also, what is this a crypto-related Known plain text attack? Regardless, I think this claim needs more clarity.

RE #5, think about how it is this different than #3. Does it add value to the overall assurance? Or would you be better off going deeper into your list of claims that you may have come up with.

**Comment by caseyschmitz** [comment]
Modifications made by @sdfrench :
4. Bitwarden adequately limits clear text exposure of secret data.
5. Bitwarden adequately ensures that secret data will be available.

**Comment by caseyschmitz** [comment]
From @sdfrench 

Here are the approved proposals:

1. Bitwarden prevents network eavesdropping during client-server communications.
2. Bitwarden is acceptably secure against login attacks.
3. Bitwarden prevents unauthorized access to secret data.
4. Bitwarden adequately limits clear text exposure of user's secret data.
5. Bitwarden adequately ensures the availability of secret data

**Comment by caseyschmitz** [comment]
Here's a Lucid Chart document that we can use to build the arguments.
https://www.lucidchart.com/documents/edit/7c09c109-b252-4092-a1b0-3a67f4825ecd/0_0

**Comment by sdfrench** [comment]
5 cases Identified and approved, this can be closed
