### ISSUE TITLE
Prepare an argument in support of the claims that would be convincing in your assumed/hypothetical operational environment. Document this argument and the needed evidence using an assurance case for each of the claims.

### ISSUE THREAD

**Issue by caseyschmitz** [caseyschmitz/CYBR8420-GotRoot#36]

**Comment by sdfrench** [comment]
Here are some links you may find helpful. 

Bitwarden sites:
[marketing](https://www.bitwarden.com/) 
[FAQs](https://help.bitwarden.com/)
[Forums](https://community.bitwarden.com/)
[GitHub](https://github.com/bitwarden)
[Blog](https://blog.bitwarden.com/)
[Blog Article on organizations](https://blog.bitwarden.com/password-sharing-is-here-organizations-cf9e7a2098d2)

Bitwarden Reviews
[PCMag](https://www.pcmag.com/review/368942/bitwarden)
[ProPrivacy](https://proprivacy.com/password-managers/bitwarden-review)
[Electric Monk](https://www.electricmonk.nl/log/2018/05/01/a-short-security-review-of-bitwarden/)
[Opensource.com](https://opensource.com/article/18/3/behind-scenes-bitwarden)

Other Managers
[1Password Security Design](https://1password.com/files/1Password-White-Paper.pdf)
[SANs Best Practices Paper](https://www.sans.org/reading-room/whitepapers/bestprac/paper/36755)
[Password Managers Under the Hood](https://www.ise.io/casestudies/password-manager-hacking/)
[1Password Security Review](https://blog.elcomsoft.com/2017/08/attacking-the-1password-master-password-follow-up/)
[LastPass Security Review](https://palant.de/2018/07/09/is-your-lastpass-data-really-safe-in-the-encrypted-online-vault/)
[KeePass Help](https://keepass.info/help/base/security.html)

**Comment by RBErnewein** [comment]
I see that the Assurance Case Diagrams 2 & 3 are done, did we decide who was taking 1, 4, or 5, so we avoid duplication of effort? I have completed all my other assignments and can work on this all day.

**Comment by sdfrench** [comment]
Per discussion in class we had: 1 - Robert, 2 - done in class, 3 - Scott, 4 - Toussida, 5 -Casey. I finished up first draft of diagram 3 last night. Since no work had been started when I checked this morning I completed first draft on diagram 1.  Looks like Toussida is making good progress on 4. I will start on five after lunch if no progress has been made.

**Comment by sdfrench** [comment]
Toussida and I finished first drafts of diagrams. I uploaded to my branch and merged. I will start working on putting evidence together for each case. I will work from top down. Feel free to work on others

**Comment by caseyschmitz** [comment]
I think we're done with this task. Hypothetical evidence alignments falls into the next issue.

**Comment by Guerrias** [comment]
Alright!!!


Sent from Yahoo Mail for iPhone


On Friday, October 11, 2019, 5:19 PM, caseyschmitz <notifications@github.com> wrote:


I think we're done with this task. Hypothetical evidence alignments falls into the next issue.

**Comment by RBErnewein** [comment]
Case Diagrams have been uploaded to the images folder

**Comment by RBErnewein** [comment]
Evidence has been cited and Arguments have been Edited & Aligned. Closing Issue.
