### ISSUE TITLE
Assess the alignment of the planned evidence with that available (or can be made available) from the OSS project. Highlight the gaps.

### ISSUE THREAD

**Issue by caseyschmitz** [caseyschmitz/CYBR8420-GotRoot#37]

**Comment by Guerrias** [comment]
Hi guys,

What are we supposed to do in this part in simple English?

**Comment by caseyschmitz** [comment]
I'm still not exactly sure what he is looking for here. "planned evidence (or can be made available)" seems to suggest that we are speculating as to where we may find the evidence specifically with respect to Bitwarden - rather than in general, which is how we made the claims.

**Comment by caseyschmitz** [comment]
For example, rather than locating the exact line of code for a particular configuration (e.g. password requirements), he may simply be suggesting that we locate where in the project that configuration might be. Thoughts?

**Comment by Guerrias** [comment]
Okay I see

**Comment by RBErnewein** [comment]
Alignment complete, Weak evidence has been identified. Closing issue.
