### ISSUE TITLE
Link to your team GitHub repository that shows your internal project task assignments and collaborations to finish this task. Also, include a summary of your team reflection meeting. What issues occurred? What did you plan to change moving forward?

### ISSUE THREAD

**Issue by caseyschmitz** [caseyschmitz/CYBR8420-GotRoot#38]

**Comment by Guerrias** [comment]
I can also start to edit this section if someone didn't start then later you can take a look at and add things that I may forget or fixe some errors.

**Comment by sdfrench** [comment]
I working on getting the markdown page now I will submit to master shortly .

**Comment by Guerrias** [comment]
Okay 


Sent from Yahoo Mail for iPhone


On Friday, October 11, 2019, 4:30 PM, sdfrench <notifications@github.com> wrote:

I working on getting the markdown page now I will submit to master shortly .

**Comment by caseyschmitz** [comment]
@sdfrench have you committed anything for the summary of our reflection meeting?

**Comment by sdfrench** [comment]
I have not documented anything in the markdown file yet. Does someone want to run with that? I want to get started on evidence once diagrams are finalized.

**Comment by caseyschmitz** [comment]
I'm about to head home from work but I'll start on this as soon as I get there.

**Comment by RBErnewein** [comment]
Added the link for the assignments: Issue page to the: Project Task Assignments and Collaborations header.

We just need to add the Team Reflection Meeting summary as a comment here to close this issue.

**Comment by RBErnewein** [comment]
Team Reflection link:
https://github.com/caseyschmitz/CYBR8420-GotRoot/blob/master/SoftwareAssuranceCases.md#team-reflections
