### ISSUE TITLE
A short summary of your code review strategy.

### ISSUE THREAD

**Issue by caseyschmitz** [caseyschmitz/CYBR8420-GotRoot#61]
What challenges did you anticipate and how did your code review strategy attempt to address those challenges?

**Comment by caseyschmitz** [comment]
SonarSource has a useful library of rules that it uses in a variety of its products to identify vulnerabilities, bugs, security hot-spots, and bad code. Here's the TypeScript library: https://rules.sonarsource.com/typescript

**Comment by caseyschmitz** [comment]
I intend to move forward with static analysis of the CLI client aided by SonarTS, a TypceScript static analyzer developed by SonarSource. Here's a link to the NPM package: https://www.npmjs.com/package/tslint-sonarts

**Comment by Guerrias** [comment]
We define a list of error we will be looking for during the manual code review. My concern is that we don't have a pattern to make comparison with the code source, so I wonder if we can use the checklist strategy.
